block.settings.active_students:
  type: block_settings
  label: 'Active students block'
  mapping:
    limit:
      type: integer
      label: 'Limit'

student_data_handler.settings:
  type: config_object
  label: 'Student Data Handler settings'
  mapping:
    example:
      type: string
      label: 'Example'
