<?php

/**
 * @file
 * Primary module hooks for Student Data Handler module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Session\AccountInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function student_data_handler_theme($existing, $type, $theme, $path) {
  $information = [
    'active_student_list' => [
      'render_element' => 'children',
      'template' => 'active-student-list',
      'path' => $path . '/templates',
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];
  return $information;
}

/**
 * Implements hook_user_logout().
 */
function student_data_handler_user_logout(AccountInterface $account) {
  Cache::invalidateTags(['active:users']);
}

/**
 * Implements hook_user_login().
 */
function student_data_handler_user_login(UserInterface $account) {
  Cache::invalidateTags(['active:users']);
}
